plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - Hadaria.md
  - HerobrineOrg.md
  - PixWorld.md
  - RinaOrc.md

theme: jekyll-theme-leap-day